### ISSUE TITLE
FubarinoSD won't talk to VB.NET serial interface

### ISSUE THREAD

**Issue by randomrichard** [fubarino/fubarino.github.com#12]
I have spent several months using FubarinoSD, communicating with it via USB serial using a freeware PC terminal called "Realterm". No problems there. However, to collect files of data from the SD I now need to use a VB.NET2012  terminal. This VB.NET terminal works fine with an Arduino Due and can send but not receive from the SD. However the SD is faster and I need to use it. This is using essentially identical software in the Due and the SD (I use UECIDE). Please explain how I can overcome this apparent bug in the SD. I have posted example software on the Fubarino SD forum as
"randomrichard" yesterday.

**Comment by EmbeddedMan** [comment]
Although the root issue here is not yet solved (the problem with the gConnected variable in the chipKIT core USB stack) I'm going to close this issue because it is not specific to Fubarino, and is better covered in the main chipKIT GitHub issues list. At least randomrichard got his problem fixed by the workaround Jacob suggested.
