### ISSUE TITLE
Real Time Clock on Fubarino SD

### ISSUE THREAD

**Issue by christophe-dupriez** [fubarino/fubarino.github.com#8]
Hi! We are trying to take advantage of Fubarino SD RTC.
We changed the bootloader so the BoardConfig.h so we have now:
#pragma config FSOSCEN  = ON
within
#elif defined(_BOARD_FUBARINO_SD_512K_USB_)
We uploaded the new bootloader with an ICD3 and reuploaded the ChipKit sketch.
This sketch makes an GPRS transaction and get the date/time from the network.
This works.
But the time does not change within the RTC and we do not see the Cristal waves with an oscilloscope.
The class used is RTCC from Majenko.

Any idea would be very very welcome!

Christophe

**Comment by EmbeddedMan** [comment]
This issue appears to have been solved - solution on the forum.

**Comment by JacobChrist** [comment]
It would be nice to add a link to this thread to the form so that someone
searching the issue list can easily find the solution.

On Sat, Jan 17, 2015 at 8:22 AM, Brian Schmalz <notifications@github.com>
wrote:

> Closed #8 <https://github.com/fubarino/fubarino.github.com/issues/8>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fubarino/fubarino.github.com/issues/8#event-220520541>
> .
>



-- 
Jacob Christ
*ProLinear/PONTECH, Inc.*
1-877-985-9286 Phone
1-413-235-1651 Fax
http://www.pontech.com
